# Generated by Django 3.0.6 on 2020-06-06 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200525_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empdetails',
            name='phone_no',
            field=models.CharField(max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name='empdetails',
            name='salary',
            field=models.BigIntegerField(),
        ),
    ]
