# Generated by Django 3.0.6 on 2020-06-06 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200606_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empdetails',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
