# Generated by Django 3.0.6 on 2020-06-06 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0004_auto_20200606_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empdetails',
            name='dno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.dept'),
        ),
        migrations.AlterField(
            model_name='empdetails',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='empdetails',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.availablepost'),
        ),
        migrations.AlterField(
            model_name='empdetails',
            name='supervisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='hop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
