# Generated by Django 3.0.6 on 2020-06-09 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200606_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='budget',
            field=models.BigIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('name', 'location')},
        ),
        migrations.CreateModel(
            name='project_img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media')),
                ('pro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.project')),
            ],
        ),
    ]
