# Generated by Django 3.0.6 on 2020-06-10 04:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0006_auto_20200609_1328'),
    ]

    operations = [
        migrations.CreateModel(
            name='empmessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date', models.DateField()),
                ('status', models.CharField(default='unread', max_length=20)),
                ('reciver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.empdetails')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
