# Generated by Django 3.0.5 on 2020-06-04 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructionmaterial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tools_issued_details',
            name='issued_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tools_issued_details',
            name='returned_date',
            field=models.DateField(),
        ),
    ]
