# Generated by Django 3.0.6 on 2020-06-11 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructionmaterial', '0002_auto_20200604_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='mat_to_project',
            name='used_qunatity',
            field=models.IntegerField(default=0),
        ),
    ]
